name: sfrmaker
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython
  - matplotlib
  - pyyaml
  - numpy
  - pandas
  - scipy
  - xarray
  - geopandas
  - gdal
  - fiona
  - rasterio
  - rasterstats
  - shapely
  - rtree
  - pyproj>=2.2
  - pyshp
  - netcdf4
  - pytest
  - pip
  - pip:
    - gis-utils
    - git+git://github.com/modflowpy/flopy@develop
    - git+git://github.com/aleaf/modflow-export@develop

